name: 'SCC Complexity Check'
description: 'Automatically analyzes code complexity using the SCC tool when a Pull Request is opened, providing metrics about complexity and lines of code differences between branches'
author: 'Azion Technologies'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Run SCC Complexity Check
      shell: bash
      run: |
        # Run the SCC complexity check script directly
        cd ${{ github.action_path }}
        ./.github/workflows/scc_check.yml
